filebeat.inputs:
  - type: filestream
    id: edge-events
    paths:
      - /var/log/neh/nginx-events.jsonl
    parsers:
      - ndjson:
          overwrite_keys: true
          add_error_key: true
    fields:
      service: edge
      dataset: neh.edge
    fields_under_root: true

  - type: filestream
    id: honeypot-events
    paths:
      - /var/log/neh/honeypot.jsonl
    parsers:
      - ndjson:
          overwrite_keys: true
          add_error_key: true
    fields:
      service: honeypot
      dataset: neh.honeypot
    fields_under_root: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  indices:
    - index: "neh-events-%{+yyyy.MM.dd}"

setup.template.enabled: false
setup.ilm.enabled: false
